"""DVC stage `eda`: summarise the clean six-feature table.

Writes a Markdown report for people and a JSON summary DVC tracks as metrics.
"""

from __future__ import annotations

import argparse
import json
import logging

import pandas as pd

from milk_adulteration.config import FEATURES, PURE_CLASS, load_params, resolve

log = logging.getLogger(__name__)


def md_table(df: pd.DataFrame, floatfmt: str = "{:.4f}") -> str:
    cols = [df.index.name or "", *map(str, df.columns)]
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for idx, row in df.iterrows():
        cells = [floatfmt.format(v) if isinstance(v, float) else str(v) for v in row]
        lines.append("| " + " | ".join([str(idx), *cells]) + " |")
    return "\n".join(lines)


def summarise(df: pd.DataFrame) -> dict:
    pure = df[df["adulterant"] == PURE_CLASS]
    pure_mean, pure_std = pure[FEATURES].mean(), pure[FEATURES].std()

    # Mean shift of each adulterant from pure milk, in pure-milk standard deviations.
    shift = (
        df[df["adulterant"] != PURE_CLASS].groupby("adulterant")[FEATURES].mean() - pure_mean
    ) / pure_std

    return {
        "rows": len(df),
        "positives": int(df["is_adulterated"].sum()),
        "positive_rate": float(df["is_adulterated"].mean()),
        "class_counts": df["adulterant"].value_counts().to_dict(),
        "feature_stats": df[FEATURES].describe().T.to_dict(orient="index"),
        "shift_z": shift.round(3).to_dict(orient="index"),
        "flag_rate_by_collection_point": (
            df.groupby("collection_point")["is_adulterated"].mean().round(4).to_dict()
        ),
        "feature_corr": df[FEATURES].corr().round(3).to_dict(),
    }


def render(s: dict) -> str:
    counts = pd.Series(s["class_counts"], name="rows").to_frame()
    counts.index.name = "class"
    stats = pd.DataFrame(s["feature_stats"]).T[["mean", "std", "min", "max"]]
    stats.index.name = "feature"
    shift = pd.DataFrame(s["shift_z"]).T[FEATURES]
    shift.index.name = "adulterant"
    flags = pd.Series(s["flag_rate_by_collection_point"], name="flag_rate").to_frame()
    flags.index.name = "collection_point"
    corr = pd.DataFrame(s["feature_corr"])[FEATURES]
    corr.index.name = "feature"

    thin = counts[(counts.index != PURE_CLASS) & (counts["rows"] < 300)]
    return f"""# EDA: Indian Milk Adulteration Dataset (six field features)

Generated by `dvc repro eda`. Source data is **synthetic** (simulated from FSSAI/BIS
standards); any result on it must be reported as synthetic.

- Rows: **{s["rows"]}**, adulterated: **{s["positives"]}** ({s["positive_rate"]:.1%})
- Stage 2 classes below the 300-sample augmentation target: **{len(thin)}/{len(counts) - 1}**
  (largest has {int(counts.drop(PURE_CLASS)["rows"].max())} rows)

## Class balance (v1 classes)

{md_table(counts)}

## Feature ranges

{md_table(stats)}

## Adulterant signal: mean shift from pure milk (in pure-milk SDs)

Values near 0 mean the adulterant barely moves that reading. Rows with no cell
beyond about ±1 are hard to detect from field readings alone.

{md_table(shift, "{:+.2f}")}

## Flag rate by collection point

{md_table(flags)}

## Feature correlation

{md_table(corr, "{:+.2f}")}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    p = load_params()["eda"]

    df = pd.read_csv(resolve(p["input"]))
    s = summarise(df)
    report, metrics = resolve(p["report"]), resolve(p["metrics"])
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(render(s))
    metrics.write_text(
        json.dumps(
            {k: s[k] for k in ("rows", "positives", "positive_rate", "class_counts")}, indent=2
        )
        + "\n"
    )
    log.info("Wrote %s and %s", report, metrics)


if __name__ == "__main__":
    main()
