"""DVC stage `stress_test`: probe the model with physics, not with more synthetic data.

These are generated samples, not real ones. They check two things the synthetic
training data cannot:

1. False alarms on pure milk spread across *published* normal ranges, which are
   wider than the synthetic data's pure-milk ranges.
2. Detection of water added by the physical mixing law at low doses.

Plus a one-reading-at-a-time sweep that shows which reading drives false alarms.
"""

from __future__ import annotations

import argparse
import json
import logging
from typing import Any

import numpy as np
import pandas as pd

from milk_adulteration.config import FEATURES, PURE_CLASS, load_params, resolve
from milk_adulteration.models.cascade import Cascade

log = logging.getLogger(__name__)


def pure_samples(ranges: dict[str, list[float]], n: int, rng: np.random.Generator) -> pd.DataFrame:
    return pd.DataFrame({f: rng.uniform(*ranges[f], n) for f in FEATURES})


def add_water(df: pd.DataFrame, water: dict[str, float], w: float) -> pd.DataFrame:
    return pd.DataFrame({f: (1 - w) * df[f] + w * water[f] for f in FEATURES})


def run(model: Cascade, train_pure: pd.DataFrame, p: dict[str, Any]) -> dict[str, Any]:
    rng = np.random.default_rng(p["seed"])
    train_range = {f: (float(train_pure[f].min()), float(train_pure[f].max())) for f in FEATURES}

    populations, accepted = {}, []
    for name, ranges in p["populations"].items():
        pure = pure_samples(ranges, p["samples"], rng)
        flagged = model.predict(pure)["is_adulterated"].to_numpy()
        inside = np.all([pure[f].between(*train_range[f]) for f in FEATURES], axis=0)
        populations[name] = {
            "range": {f: list(map(float, ranges[f])) for f in FEATURES},
            "false_alarm_rate": float(flagged.mean()),
            "inside_training_range": int(inside.sum()),
            "false_alarm_rate_inside_training_range": (
                float(flagged[inside].mean()) if inside.any() else None
            ),
        }
        accepted.append(pure[~flagged])

    # Sweep: start inside both ranges, move one reading across its published range.
    ranges = p["populations"][p["sweep_population"]]
    lo = {f: max(ranges[f][0], train_range[f][0]) for f in FEATURES}
    hi = {f: min(ranges[f][1], train_range[f][1]) for f in FEATURES}
    base = pd.DataFrame({f: rng.uniform(min(lo[f], hi[f]), hi[f], 500) for f in FEATURES})
    sweep = {}
    for f in FEATURES:
        values = np.linspace(*ranges[f], p["sweep_points"])
        sweep[f] = [
            (float(v), float(model.predict(base.assign(**{f: v}))["is_adulterated"].mean()))
            for v in values
        ]

    accepted_all = pd.concat(accepted, ignore_index=True)
    water = {}
    for w in p["water_fractions"]:
        pred = model.predict(add_water(accepted_all, p["water"], w))
        hit = pred["is_adulterated"].to_numpy()
        named = (pred.loc[hit, "adulterant"] == "water").mean() if hit.any() else 0.0
        water[str(w)] = {"flagged": float(hit.mean()), "named_water": float(named)}

    return {
        "populations": populations,
        "pure_false_alarm_rate": float(
            np.mean([v["false_alarm_rate"] for v in populations.values()])
        ),
        "train_pure_range": train_range,
        "sweep_population": p["sweep_population"],
        "sweep": sweep,
        "water": water,
    }


def render(r: dict[str, Any], p: dict[str, Any]) -> str:
    names = list(r["populations"])
    head = " | ".join(f"{n.title()} published range" for n in names)
    rows = [
        f"| {f} | "
        + " | ".join(
            f"{r['populations'][n]['range'][f][0]:g} to {r['populations'][n]['range'][f][1]:g}"
            for n in names
        )
        + f" | {r['train_pure_range'][f][0]:.4g} to {r['train_pure_range'][f][1]:.4g} |"
        for f in FEATURES
    ]

    def pct(v: float | None) -> str:
        return "n/a" if v is None else f"{v:.1%}"

    fa_rows = [
        f"| {n} | **{pct(m['false_alarm_rate'])}** | {m['inside_training_range']} | "
        f"{pct(m['false_alarm_rate_inside_training_range'])} |"
        for n, m in r["populations"].items()
    ]
    sweep_rows = []
    for f, pts in r["sweep"].items():
        worst = max(rate for _, rate in pts)
        cells = " · ".join(f"{v:.4g}: {rate:.0%}" for v, rate in pts)
        sweep_rows.append(f"| {f} | {worst:.0%} | {cells} |")
    water_rows = [
        f"| {float(w):.0%} | {m['flagged']:.1%} | {m['named_water']:.1%} |"
        for w, m in r["water"].items()
    ]
    nl = "\n"
    return f"""# Stress test (physics-based, not real samples)

Generated by `dvc repro stress_test`. Samples here are **generated**, not measured.
They probe what the synthetic training data cannot: pure milk across *published*
normal ranges, and water added by the physical mixing law. Real lab samples are
still needed; see GUIDE.md.

Caveat: training widens pure milk onto similar published ranges
(`augment.widen_pure`), so passing section 1 shows the widening took effect; it is
not independent evidence about real milk.

## 1. False alarms on pure milk

{p["samples"]} pure samples per population, each reading drawn uniformly and
independently from its published normal range.

| Population | Flagged | Inside synthetic pure ranges | Flagged among those |
|---|---|---|---|
{nl.join(fa_rows)}

| Reading | {head} | Synthetic pure-milk range (training, before widening) |
|---|{"---|" * len(names)}---|
{nl.join(rows)}

## 2. Which reading causes false alarms ({r["sweep_population"]} milk)

Each row starts from pure samples inside both ranges and moves one reading across
its published range. Cells show the value, then the share flagged.

| Reading | Worst | Sweep |
|---|---|---|
{nl.join(sweep_rows)}

## 3. Water added by the mixing law

Water mixed into the pure samples the model accepted (all populations):
reading′ = (1 − w) · reading + w · water, with water at fat 0, SNF 0, density 0.998,
pH 7.0, freezing point 0 °C and conductivity 0.5 mS/cm.

| Added water | Flagged | Named "water" when flagged |
|---|---|---|
{nl.join(water_rows)}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    params = load_params()
    p = params["stress_test"]
    model = Cascade.load(resolve(params["train"]["model"]))
    train = pd.read_csv(resolve(params["split"]["output_dir"]) / "train.csv")
    r = run(model, train[train["adulterant"] == PURE_CLASS], p)
    resolve(p["report"]).write_text(render(r, p))
    summary = {
        "pure_false_alarm_rate": {n: m["false_alarm_rate"] for n, m in r["populations"].items()},
        "water_flagged": {w: m["flagged"] for w, m in r["water"].items()},
    }
    resolve(p["metrics"]).write_text(json.dumps(summary, indent=2) + "\n")
    log.info("Pure-milk false alarms: %s", summary["pure_false_alarm_rate"])


if __name__ == "__main__":
    main()
